<p><b>¡IMPORTANTE!</b></p>
<p>Active las cookies de su navegador para el correcto funcionamiento de la web.</p>
<br/>
<p><b>1. ¿QUÉ TIPO DE PÁGINA ES ESTA?</b></p>
<p>"www.pachuparselosdedos.com" es una web de venta de productos on-line por medio de transferencia bancaria, que ofrece un surtido de productos tales como jamón, queso, vino, etc.</p>
<br/>
<p><b>2. ¿QUÉ TENGO QUE HACER ANTES DE COMPRAR?</b></p>
<p>Lo primero que debe de hacer para comprar en la web es rellenar el formulario de registro, el cual podrá acceder mediante el enlace de la parte superior derecha de la pantalla que indica "Registrate"</p>
<p>Una vez este registrado, podra realizar su compra después de logearse</p>
<br/>
<p><b>3. ¿DÓNDE ESTAN LOS PRODUCTOS?</b></p>
<p>Para acceder a los productos deberá seleccionar en el menú de la izquierda la opción de productos y se le desplegará un nuevo submenú con los tipos de productos que hay. Seleccione uno para divisar los productos.</p>
<br/>
<p><b>4. ¿CÓMO GUARDO LOS PRODUCTOS QUE QUIERO COMPRAR?</b></p>
<p>Al lado de cada producto viene un desplegable para seleccionar la cantidad de ese producto que quiere añadir a su carro de la compra, una vez seleccionada pulse en el botón "Añadir" para almacenarlo en su carro de la compra.</p>
<br/>
<p><b>5. ¿Y SI ME LO PIENSO Y QUIERO COMPRAR MENOS CANTIDAD DE ESE PRODUCTO?</b></p>
<p>Tan simple como ir a la ventana que se ha desplegado con el carrito, seleccionar la cantidad de unidades a quitar y pulsar el botón de "QUITAR".</p>
<br/>
<p><b>6. CERRÉ SIN QUERER LA VENTANA DEL CARRITO, ¿TENGO QUE VOLVER A HACER DE NUEVO LA COMPRA?</b></p>
<p>No, su compra sigue almacenada, tan solo tendrá que pinchar en el enlace en la parte superior a la derecha que indica "Ir al carrito" y se le volverá a abrir su carrito sin problemas.</p>
<br/>
<p><b>7. ¿CÓMO CONFIRMO UNA COMPRA?</b></p>
<p>Para confirmar una compra, en la ventana del carrito deberá pulsar el enlace de comprar que aparece al final de la lista. Esto le llevará a una nueva pantalla, donde se le mostrarán los datos de su compra.</p>
<p>En caso de que no sean los que quería, pulse "Cancelar", si por el contrario son los correctos, pulse "Confirmar".</p>
<p>Seguidamente se le mostrará otra pantalla indicandole que finalizó la compra y se le envio los datos de la compra y los datos de pago a su correo.</p>
<br/>
<p><b>8. YA TERMINÉ DE COMPRAR Y QUIERO SALIR DE LA PÁGINA, ¿DEBO HACER ALGO ANTES?</b></p>
<p>Para mayor seguridad de que sus datos no queden almacenador en el ordenador, es aconsejable que antes de salir vaya a la parte superior derecha de la pantalla y pulse en "Desconectar".</p>
<br/>